[package]
name = "sphero-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8"

[dev-dependencies]
btleplug = "0.7"
tokio =  { version = "1", features = ["full"] }
